name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.4.4
  - seaborn=0.11.2
  - pandas=1.1.5
  - pip=22.2.2
  - pandas-profiling=3.6.2
  - pyarrow=10.0.1 
  - pip:
      - wandb==0.12.21