name: test_regression_model
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=22.2.2
  - pandas=1.1.5
  - scikit-learn=0.24.2
  - matplotlib=3.5.2
  - pillow=9.2.0
  - pip:
    - mlflow==2.1.1
    - wandb==0.13.8
