name: nyc_airbnb
channels:
  - defaults
dependencies:
  - pip=22.2.2
  - pip:
  - mlflow
  - ipython==7.21.0
  - notebook==6.2.0
  - jupyterlab==3.0.10
  - cookiecutter==1.7.2
  - hydra-core==1.3.1
  - matplotlib==3.5.2
  - pandas=1.4.4
  - wandb==0.13.8

