name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.1.5
  - pip=22.2.2
  - mlflow=2.1.1
  - scikit-learn=0.24.2
  - matplotlib=3.5.2
  - pillow=9.2.0
  - pip:
      - wandb==0.13.8
